// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: proto/dlp.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InspectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Direction     string                 `protobuf:"bytes,2,opt,name=direction,proto3" json:"direction,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectRequest) Reset() {
	*x = InspectRequest{}
	mi := &file_proto_dlp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectRequest) ProtoMessage() {}

func (x *InspectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dlp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectRequest.ProtoReflect.Descriptor instead.
func (*InspectRequest) Descriptor() ([]byte, []int) {
	return file_proto_dlp_proto_rawDescGZIP(), []int{0}
}

func (x *InspectRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *InspectRequest) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *InspectRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *InspectRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *InspectRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *InspectRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type Verdict struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Action          string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	TransformedBody []byte                 `protobuf:"bytes,2,opt,name=transformed_body,json=transformedBody,proto3" json:"transformed_body,omitempty"`
	Reason          string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Verdict) Reset() {
	*x = Verdict{}
	mi := &file_proto_dlp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Verdict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Verdict) ProtoMessage() {}

func (x *Verdict) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dlp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Verdict.ProtoReflect.Descriptor instead.
func (*Verdict) Descriptor() ([]byte, []int) {
	return file_proto_dlp_proto_rawDescGZIP(), []int{1}
}

func (x *Verdict) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Verdict) GetTransformedBody() []byte {
	if x != nil {
		return x.TransformedBody
	}
	return nil
}

func (x *Verdict) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_proto_dlp_proto protoreflect.FileDescriptor

const file_proto_dlp_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/dlp.proto\x12\x03dlp\"\x85\x02\n" +
	"\x0eInspectRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1c\n" +
	"\tdirection\x18\x02 \x01(\tR\tdirection\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12:\n" +
	"\aheaders\x18\x05 \x03(\v2 .dlp.InspectRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x06 \x01(\fR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"d\n" +
	"\aVerdict\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12)\n" +
	"\x10transformed_body\x18\x02 \x01(\fR\x0ftransformedBody\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason2<\n" +
	"\fDLPInspector\x12,\n" +
	"\aInspect\x12\x13.dlp.InspectRequest\x1a\f.dlp.VerdictB=Z;github.com/GenAI-DLP/dlp-proxy-server/internal/dlpclient/pbb\x06proto3"

var (
	file_proto_dlp_proto_rawDescOnce sync.Once
	file_proto_dlp_proto_rawDescData []byte
)

func file_proto_dlp_proto_rawDescGZIP() []byte {
	file_proto_dlp_proto_rawDescOnce.Do(func() {
		file_proto_dlp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dlp_proto_rawDesc), len(file_proto_dlp_proto_rawDesc)))
	})
	return file_proto_dlp_proto_rawDescData
}

var file_proto_dlp_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_dlp_proto_goTypes = []any{
	(*InspectRequest)(nil), // 0: dlp.InspectRequest
	(*Verdict)(nil),        // 1: dlp.Verdict
	nil,                    // 2: dlp.InspectRequest.HeadersEntry
}
var file_proto_dlp_proto_depIdxs = []int32{
	2, // 0: dlp.InspectRequest.headers:type_name -> dlp.InspectRequest.HeadersEntry
	0, // 1: dlp.DLPInspector.Inspect:input_type -> dlp.InspectRequest
	1, // 2: dlp.DLPInspector.Inspect:output_type -> dlp.Verdict
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_dlp_proto_init() }
func file_proto_dlp_proto_init() {
	if File_proto_dlp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dlp_proto_rawDesc), len(file_proto_dlp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dlp_proto_goTypes,
		DependencyIndexes: file_proto_dlp_proto_depIdxs,
		MessageInfos:      file_proto_dlp_proto_msgTypes,
	}.Build()
	File_proto_dlp_proto = out.File
	file_proto_dlp_proto_goTypes = nil
	file_proto_dlp_proto_depIdxs = nil
}
